#!/bin/bash
IPADDRESS=`ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
MAJORVER=`rpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release)`
PROCARC=`uname -i`
SOURCEDIR="./Cockatrice"
EXAMPLESQLFILE="$SOURCEDIR/servatrice/servatrice.sql"
EXAMPLEINIFILE="$SOURCEDIR/servatrice/servatrice.ini.example"
PRECONFINIFILE="./servatrice.ini"
SITEZIP="servatriceadmin.tgz"
WEBSITEDATAURL="http://www.woogerworks.com/cockatrice/$SITEZIP"
HTTPDHOMEPATH="/var/www/html"

remove_existingsource()
{
        if [ -d $SOURCEDIR ]
        then
                rm -rf $SOURCEDIR
        fi
}

define_trustlevel()
{
	[ -z $1 ] && PASSEDTRUSTVALUE="untrust"
	[ ! -z $1 ] && PASSEDTRUSTVALUE=${1,,}
	case $PASSEDTRUSTVALUE in
		trust)
			TRUSTEXISTINGSOURCE="yes"
			;;
		untrust)
			TRUSTEXISTINGSOURCE="no"
			;;
		*)
			echo "Usage: install <method> <existingsourcetrust>"
	                echo "(ERROR)Unknown existing source trust type passed, please use: [trust,untrust]"
			exit 2
			;;
	esac
}

install_server()
{
	cd ~
	sudo yum -y groupinstall "development tools"
	sudo rpm -Uvh http://dl.fedoraproject.org/pub/epel/$MAJORVER/$PROCARC/epel-release-6-8.noarch.rpm
	sudo yum -y install qt-mysql qt-devel qt-mobility-devel protobuf-devel protobuf-compiler cmake28 libgcrypt-devel
	[ $TRUSTEXISTINGSOURCE == "no" ] && remove_existingsource
	[ ! -d $SOURCEDIR ] && wget http://www.woogerworks.com/files/Cockatrice_20130227.zip
	[ -f "Cockatrice_20130227.zip" ] && Cockatrice_20130227.zip
	cd Cockatrice
	[ -d "./build" ] && sudo rm -rf ./build
	mkdir build
	cd build
	cmake28 -DWITH_SERVER=1 -DWITHOUT_CLIENT=1 ..
	make
	sudo make install
	sed -e "s/number_pools=1/number_pools=0/" ../servatrice/servatrice.ini.example > ~/servatrice.ini
}

install_client()
{
	cd ~
	sudo yum -y groupinstall "development tools"
	sudo rpm -Uvh http://dl.fedoraproject.org/pub/epel/$MAJORVER/$PROCARC/epel-release-6-8.noarch.rpm
	sudo yum -y install qt-devel qt-mobility-devel protobuf-devel protobuf-compiler cmake28
	[ $TRUSTEXISTINGSOURCE == "no" ] && remove_existingsource
	[ ! -d $SOURCEDIR ] && wget http://www.woogerworks.com/files/Cockatrice_20130214.zip
        [ -f "Cockatrice_20130214.zip" ] && unzip Cockatrice_20130214.zip
	cd Cockatrice
	[ -d "./build" ] && sudo rm -rf ./build
	mkdir build
	cd build
	cmake28 ..
	make
	sudo make install
}

install_dbserver()
{
	sudo yum -y install git mysql-server mysql php-mysql
	cd ~
	[ $TRUSTEXISTINGSOURCE == "no" ] && remove_existingsource
	[ ! -d $SOURCEDIR ] && wget http://www.woogerworks.com/files/Cockatrice_20130214.zip
        [ -f "Cockatrice_20130214.zip" ] && unzip Cockatrice_20130214.zip
	if [ ! -f $EXAMPLESQLFILE ]
	then
       		remove_existingsource
		[ ! -d $SOURCEDIR ] && wget http://www.woogerworks.com/files/Cockatrice_20130214.zip
	        [ -f "Cockatrice_20130214.zip" ] && unzip Cockatrice_20130214.zip
	fi
	sudo service mysqld start
	sudo chkconfig mysqld on
	mysqladmin -u root password 'password'
	`mysql -u root -ppassword -e "create database servatrice;"`
	`mysql -u root -ppassword -e "create user 'servatrice'@'localhost' identified by 'password';"`
	`mysql -u root -ppassword -e "grant all privileges on servatrice.* to 'servatrice'@'localhost';"`
	`mysql -u servatrice -ppassword servatrice < $EXAMPLESQLFILE`
	`mysql -u servatrice -ppassword -e "insert into servatrice.cockatrice_users (admin,name,password_sha512,active) values (1,'servatrice','jbB4kSWDmjaVzMNdU13n73SpdBCJTCJ/JYm5ZBZvfxlzbISbXir+e/aSvMz86KzOoaBfidxO0s6GVd8t00qC0TNPl+udHfECaF7MsA==',1);"`

	if [ -f $PRECONFINIFILE ]
	then
        	sed -i.bak -e "s/password=foobar/password=password/" -e "s/type=none/type=mysql/" -e "s/method=none/method=sql/" $PRECONFINIFILE
	else
        	if [ ! -f $EXAMPLEINIFILE ]
	        then
        	        remove_existingsource
	        	[ ! -d $SOURCEDIR ] && wget http://www.woogerworks.com/files/Cockatrice_20130214.zip
		        [ -f "Cockatrice_20130214.zip" ] && unzip Cockatrice_20130214.zip
		fi
        	sed -e "s/password=foobar/password=password/" -e "s/type=none/type=mysql/" -e "s/method=none/method=sql/" $EXAMPLEINIFILE > $PRECONFINIFILE
	fi
}

install_webserver()
{
	cd ~
	sudo yum -y install httpd php php-mysql
	service httpd start
	sudo chkconfig httpd on
}

install_website()
{
	cd ~
	sudo yum -y install tar gzip
	if [ -f ./$SITEZIP ] 
	then
		rm -f ./$SITEZIP
	fi
	wget $WEBSITEDATAURL
	if [ -f ./$SITEZIP ]
	then
		sudo tar zxf ./$SITEZIP -C $HTTPDHOMEPATH
		if [ -f $HTTPDHOMEPATH/.config ]
		then
			sudo sed -i.bak -e "s/dbserver=<dbserveraddress>/dbserver=localhost/" -e "s/dbusername=<dbusername>/dbusername=servatrice/" -e "s/dbpassword=<dbpassword>/dbpassword=password/" $HTTPDHOMEPATH/.config
		fi
	fi
}

define_trustlevel $2
[ ! -z "$1" ] && INSTALLMETHOD=${1,,} 
case $INSTALLMETHOD in
	webserver)
		clear
		echo "WEBSERVER INSTALL (TRUST EXISTING SOURCE: $TRUSTEXISTINGSOURCE)"
		echo This install script will download and install the apache
		echo web server and configure it for use with the servatrice
		echo application. It is designed to be run on a CentOS 6
		echo operating system. You *MUST* have internet access and also
		echo have sudo rights.
		read -p "Press any key to continue... " -n1 -s
		echo
		
		install_webserver
		
		echo
		echo WEBSERVER INSTALL COMPLETE
		echo You can now access the webserver by going to:
		echo http://$IPADDRESS
		
		;;
	website)
		clear
		echo "WEBSITE INSTALL (TRUST EXISTING SOURCE: $TRUSTEXISTINGSOURCE)"
		echo This install script will download and set in place a basic
		echo servatrice web administration site for use with the
		echo servatrice application.  It is designed to be run on a
		echo CentOS 6 operating system.  You *MUST* have internet access
		echo and also have sudo rights.
		read -p "Press any key to continue... " -n1 -s
		echo
		
		install_website
			
		echo
		echo WEBSITE INSTALL COMPLETE
		echo You can now access the website by going to: http://$IPADDRESS
		echo Please remember to update the $HTTPDHOMEPATH/.config file for any 
		echo site specific configuration changes necessary.
		
		;;
	client)
		clear
		echo "CLIENT INSTALL (TRUST EXISTING SOURCE: $TRUSTEXISTINGSOURCE)"
		echo This install script will download, build and install
		echo the cockatrice application.  It is designed to be run
		echo on a CentOS 6 operating system. You echo *MUST* have
		echo internet access and also have sudo rights.
		read -p "Press any key to continue... " -n1 -s
		echo

		install_client

		echo
		echo CLIENT INSTALL COMPLETE
		echo You can now start the oracle application by running: "/usr/local/bin/oracle &"
		echo You can now start the cockatrice application by running: "/usr/local/bin/cockatrice &"
		echo You should also have icons under your gnome start menu at: "Applications -> Games"

		;;
	server)
		clear
		echo "SERVER INSTALL (TRUST EXISTING SOURCE: $TRUSTEXISTINGSOURCE)"
		echo This install script will download, build and install
		echo the servatrice application.  It is designed to be run on 
		echo a CentOS 6 operating system. You *MUST* have internet 
		echo access and also have sudo rights.
		read -p "Press any key to continue... " -n1 -s
		echo

		install_server

		echo
		echo SERVER INSTALL COMPLETE
		echo You can now start the servatrice server by running: "/usr/local/bin/servatrice &"
		echo You now can connect to your new servatrice server
		echo using the following information:
		echo Host: localhost
		echo Port: 4747
		;;
	dbserver)
		clear
		echo "DATABASE SERVER INSTALL (TRUST EXISTING SOUCE: $TRUSTEXISTINGSOURCE)"
		echo This install script will download and install a
		echo mysql database server and configure it for use
		echo with the servatrice application.  It is designed to 
		echo be run on a CentOS 6 operating system. You *MUST* 
		echo have internet access and also have sudo rights.
		read -p "Press any key to continue... " -n1 -s
		echo

		install_dbserver

		echo
		echo DATABASE INSTALL COMPLETE
		echo You now can connect to your servatrice server
		echo using the following information:
		echo Host: localhost
		echo Port: 4747
		echo Player Name: servatrice
		echo Password: password
		echo
		;;
	all)
		clear
		echo "ALL INSTALL (TRUST EXISTING SOURCE: $TRUSTEXISTINGSOURCE)"
                echo This install script will download, build and install
                echo the cockatrice and servatrice  application.  As well as
		echo install a mysql database server ,configure it for use
		echo with the servatrice application. Install a web server
		echo and import a basic web site for server administration.
		echo It is designed to be run on a CentOS 6 operating system.
		echo You *MUST* have internet access and also have sudo rights.
                read -p "Press any key to continue... " -n1 -s
                echo
		
		install_client
		install_server
		install_dbserver
		install_webserver
		install_website
		
		echo
                echo INSTALL COMPLETE
                echo You can now get to the administration site by going to: http://$IPADDRESS
		echo You can now start the servatrice server by running: "/usr/local/bin/servatrice &"
                echo You can now start the oracle application  by running: "/usr/local/bin/oracle &"
                echo You can now start the cockatrice application by running: "/usr/local/bin/cockatrice &"
                echo You should also have icons under your gnome start menu at: "Applications -> Games"
                echo You now can connect to your servatrice server
                echo using the following information:
                echo Host: localhost
                echo Port: 4747
                echo Player Name: servatrice
                echo Password: password
                echo
		;;
	*)
		echo "Usage: install <method> <existingsourcetrust>"
		echo "(ERROR)Unknown install method passed, please use: [client,server,dbserver,webserver,website,all]"
		exit 1
		;;
esac
